-- Canonical schema for the active Supabase adapter.
-- The Express server should use SUPABASE_SERVICE_ROLE_KEY server-side;
-- never expose that key to the browser.

create table if not exists products (
  id bigint generated by default as identity primary key,
  barcode text not null default '',
  barcode_2 text not null default '',
  stock_no text not null default '',
  product_name text not null,
  category text not null default 'Uncategorized',
  department text not null default '',
  floor text not null default '',
  row text not null default '',
  shelf text not null default '',
  level text not null default '0',
  loc text not null default '',
  location_storage text not null default '',
  qty integer not null default 0 check (qty >= 0),
  status text not null default 'UNMAPPED',
  custom boolean not null default false,
  last_modified_by text not null default 'System Import',
  created_at timestamptz not null default now()
);

create table if not exists users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password text not null, -- scrypt$<salt>$<derived-key>
  full_name text not null,
  role text not null default 'stockman' check (role in ('stockman', 'checker', 'carton_handler', 'admin', 'superadmin')),
  created_at timestamptz not null default now()
);

create index if not exists idx_products_barcode on products (lower(barcode));
create index if not exists idx_products_barcode_2 on products (lower(barcode_2));
create index if not exists idx_products_stock_no on products (lower(stock_no));
create index if not exists idx_products_barcode_exact on products (barcode);
create index if not exists idx_products_barcode_2_exact on products (barcode_2);
create index if not exists idx_products_stock_no_exact on products (stock_no);
create index if not exists idx_products_location on products (loc);
create index if not exists idx_products_name on products (lower(product_name));
create index if not exists idx_products_status on products (status);
create index if not exists idx_products_floor on products (floor);

-- Contains searches need trigram indexes; otherwise PostgreSQL scans the
-- whole catalog for each public lookup.
create extension if not exists pg_trgm;
create index if not exists idx_products_name_trgm on products using gin (product_name gin_trgm_ops);
create index if not exists idx_products_barcode_trgm on products using gin (barcode gin_trgm_ops);
create index if not exists idx_products_barcode_2_trgm on products using gin (barcode_2 gin_trgm_ops);
create index if not exists idx_products_stock_no_trgm on products using gin (stock_no gin_trgm_ops);
create index if not exists idx_products_category_trgm on products using gin (category gin_trgm_ops);
create index if not exists idx_products_department_trgm on products using gin (department gin_trgm_ops);

-- Keep the header/admin KPI distinct by SKU without transferring every row
-- through the Netlify function. A product can have multiple shelf rows.
create or replace function public.get_product_stats()
returns jsonb
language sql
stable
as $$
  with sku_rows as (
    select
      coalesce(nullif(lower(trim(barcode)), ''), nullif(lower(trim(stock_no)), ''), 'id:' || id::text) as sku_key,
      status,
      floor,
      "row",
      shelf,
      custom
    from public.products
  ),
  sku_rollup as (
    select
      sku_key,
      bool_or(
        upper(coalesce(status, '')) = 'MAPPED'
        or nullif(trim(coalesce(floor, '')), '') is not null
        or nullif(trim(coalesce("row", '')), '') is not null
        or nullif(trim(coalesce(shelf, '')), '') is not null
      ) as is_mapped,
      bool_or(custom) as is_custom
    from sku_rows
    group by sku_key
  )
  select jsonb_build_object(
    'total', count(*),
    'customCount', count(*) filter (where is_custom),
    'mappedCount', count(*) filter (where is_mapped),
    'unmappedCount', count(*) filter (where not is_mapped)
  )
  from sku_rollup;
$$;

alter table products enable row level security;
alter table users enable row level security;

-- Public catalog lookup is allowed. All writes and user access go through
-- the authenticated Express API using the server-only service-role key.
drop policy if exists products_public_read on products;
create policy products_public_read on products for select to anon, authenticated using (true);
