-- Canonical schema for the active Supabase adapter.
-- The Express server should use SUPABASE_SERVICE_ROLE_KEY server-side;
-- never expose that key to the browser.

create table if not exists products (
  id bigint generated by default as identity primary key,
  barcode text not null default '',
  barcode_2 text not null default '',
  stock_no text not null default '',
  product_name text not null,
  category text not null default 'Uncategorized',
  department text not null default '',
  floor text not null default '',
  row text not null default '',
  shelf text not null default '',
  level text not null default '0',
  loc text not null default '',
  location_storage text not null default '',
  qty integer not null default 0 check (qty >= 0),
  status text not null default 'UNMAPPED',
  custom boolean not null default false,
  last_modified_by text not null default 'System Import',
  created_at timestamptz not null default now()
);

create table if not exists users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password text not null, -- scrypt$<salt>$<derived-key>
  full_name text not null,
  role text not null default 'stockman' check (role in ('stockman', 'checker', 'carton_handler', 'admin', 'superadmin')),
  created_at timestamptz not null default now()
);

create index if not exists idx_products_barcode on products (lower(barcode));
create index if not exists idx_products_barcode_2 on products (lower(barcode_2));
create index if not exists idx_products_stock_no on products (lower(stock_no));
create index if not exists idx_products_location on products (loc);
create index if not exists idx_products_name on products (lower(product_name));

alter table products enable row level security;
alter table users enable row level security;

-- Public catalog lookup is allowed. All writes and user access go through
-- the authenticated Express API using the server-only service-role key.
drop policy if exists products_public_read on products;
create policy products_public_read on products for select to anon, authenticated using (true);
