-- Canonical schema for the active Supabase adapter.
-- The Express server should use SUPABASE_SERVICE_ROLE_KEY server-side;
-- never expose that key to the browser.

create table if not exists products (
  id bigint generated by default as identity primary key,
  barcode text not null default '',
  barcode_2 text not null default '',
  stock_no text not null default '',
  product_name text not null,
  category text not null default 'Uncategorized',
  department text not null default '',
  floor text not null default '',
  row text not null default '',
  shelf text not null default '',
  level text not null default '0',
  loc text not null default '',
  location_storage text not null default '',
  -- Physical quantity actually sitting at THIS shelf location. Multiple rows
  -- can share the same barcode/stock_no when a product occupies more than
  -- one location; each row's qty is independent.
  qty integer not null default 0 check (qty >= 0),
  -- Total units on hand for this SKU, tracked separately from any single
  -- shelf's qty above. Kept in sync across every row sharing the same
  -- barcode/stock_no. Null means it has never been set and callers should
  -- fall back to summing qty across that SKU's locations.
  on_hand_qty integer check (on_hand_qty is null or on_hand_qty >= 0),
  -- Running audit total of units removed from a mapped shelf location via a
  -- manual qty decrease in the Edit form (Product Details & Location), e.g.
  -- editing 1272 -> 1270. Kept in sync across every row sharing the same
  -- barcode/stock_no, same as on_hand_qty. Purely a record for staff to
  -- review — it is never subtracted from Actual On Hand or Not Located, so
  -- it never double-counts against those totals. Shown to staff as
  -- "Missing".
  unaccounted_qty integer not null default 0 check (unaccounted_qty >= 0),
  -- Running audit total of units added via a Quick Inventory Count "New
  -- Quantity" that exceeded the prior On Hand total. Kept in sync across
  -- every row sharing the same barcode/stock_no, same as on_hand_qty.
  -- Counted but not yet given a shelf address; drains back down as that
  -- stock gets shelved.
  not_located_qty integer not null default 0 check (not_located_qty >= 0),
  -- Timestamp supplied by the external inventory system. It represents when
  -- that system says its on-hand number was true, not a shelf edit time.
  system_on_hand_updated_at timestamptz,
  status text not null default 'UNMAPPED',
  custom boolean not null default false,
  last_modified_by text not null default 'System Import',
  created_at timestamptz not null default now()
);

-- Safe for existing Supabase projects that already created the products table.
alter table products add column if not exists system_on_hand_updated_at timestamptz;
alter table products add column if not exists on_hand_qty integer;
alter table products add column if not exists unaccounted_qty integer not null default 0;
alter table products add column if not exists not_located_qty integer not null default 0;
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'products_on_hand_qty_check'
  ) then
    alter table products add constraint products_on_hand_qty_check check (on_hand_qty is null or on_hand_qty >= 0);
  end if;
  if not exists (
    select 1 from pg_constraint where conname = 'products_unaccounted_qty_check'
  ) then
    alter table products add constraint products_unaccounted_qty_check check (unaccounted_qty >= 0);
  end if;
  if not exists (
    select 1 from pg_constraint where conname = 'products_not_located_qty_check'
  ) then
    alter table products add constraint products_not_located_qty_check check (not_located_qty >= 0);
  end if;
end $$;

create table if not exists users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password text not null, -- scrypt$<salt>$<derived-key>
  full_name text not null,
  role text not null default 'stockman' check (role in ('stockman', 'checker', 'carton_handler', 'admin', 'superadmin')),
  created_at timestamptz not null default now()
);

create index if not exists idx_products_barcode on products (lower(barcode));
create index if not exists idx_products_barcode_2 on products (lower(barcode_2));
create index if not exists idx_products_stock_no on products (lower(stock_no));
create index if not exists idx_products_barcode_exact on products (barcode);
create index if not exists idx_products_barcode_2_exact on products (barcode_2);
create index if not exists idx_products_stock_no_exact on products (stock_no);
create index if not exists idx_products_location on products (loc);
create index if not exists idx_products_name on products (lower(product_name));
create index if not exists idx_products_status on products (status);
create index if not exists idx_products_floor on products (floor);
create index if not exists idx_products_system_on_hand_updated_at on products (system_on_hand_updated_at desc);

-- Contains searches need trigram indexes; otherwise PostgreSQL scans the
-- whole catalog for each public lookup.
create extension if not exists pg_trgm;
create index if not exists idx_products_name_trgm on products using gin (product_name gin_trgm_ops);
create index if not exists idx_products_barcode_trgm on products using gin (barcode gin_trgm_ops);
create index if not exists idx_products_barcode_2_trgm on products using gin (barcode_2 gin_trgm_ops);
create index if not exists idx_products_stock_no_trgm on products using gin (stock_no gin_trgm_ops);
create index if not exists idx_products_category_trgm on products using gin (category gin_trgm_ops);
create index if not exists idx_products_department_trgm on products using gin (department gin_trgm_ops);

-- Keep the header/admin KPI distinct by SKU without transferring every row
-- through the Netlify function. A product can have multiple shelf rows.
create or replace function public.get_product_stats_v3()
returns jsonb
language sql
stable
as $$
  with sku_rows as (
    select
      coalesce(
        nullif(lower(trim(barcode)), ''),
        nullif(lower(trim(stock_no)), ''),
        'id:' || id::text
      ) as sku_key,
      status,
      floor,
      "row",
      shelf,
      custom
    from public.products
  ),
  sku_rollup as (
    select
      sku_key,
      bool_or(
        upper(coalesce(status, '')) = 'MAPPED'
        or nullif(trim(coalesce(floor, '')), '') is not null
        or nullif(trim(coalesce("row", '')), '') is not null
        or nullif(trim(coalesce(shelf, '')), '') is not null
      ) as is_mapped,
      bool_or(custom) as is_custom
    from sku_rows
    group by sku_key
  )
  select jsonb_build_object(
    'total', count(*),
    'customCount', count(*) filter (where is_custom),
    'mappedCount', count(*) filter (where is_mapped),
    'unmappedCount', count(*) filter (where not is_mapped)
  )
  from sku_rollup;
$$;

alter table products enable row level security;
alter table users enable row level security;

-- Public catalog lookup is allowed. All writes and user access go through
-- the authenticated Express API using the server-only service-role key.
drop policy if exists products_public_read on products;
create policy products_public_read on products for select to anon, authenticated using (true);

-- -------------------------------------------------------------------------
-- Inventory ledger and balance model
-- -------------------------------------------------------------------------

create table if not exists inventory_locations (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null default '',
  storage_type text not null default 'SHELF' check (storage_type in ('RECEIVING','BULK','SHELF','PICKED','DAMAGED','DISPATCHED')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists inventory_lots (
  id bigint generated by default as identity primary key,
  sku_key text not null,
  barcode text not null default '',
  stock_no text not null default '',
  product_name text not null default '',
  lot_code text not null unique,
  package_type text not null default 'EACH' check (package_type in ('EACH','CARTON','SACK','PALLET','OTHER')),
  received_qty integer not null check (received_qty > 0),
  received_at timestamptz not null default now(),
  source_reference text not null default '',
  created_by text not null default 'System',
  created_at timestamptz not null default now()
);

create table if not exists inventory_balances (
  id bigint generated by default as identity primary key,
  sku_key text not null,
  lot_id bigint not null references inventory_lots(id) on delete restrict,
  location_id bigint not null references inventory_locations(id) on delete restrict,
  qty_on_hand integer not null default 0 check (qty_on_hand >= 0),
  qty_reserved integer not null default 0 check (qty_reserved >= 0 and qty_reserved <= qty_on_hand),
  updated_at timestamptz not null default now(),
  unique (lot_id, location_id)
);

create table if not exists inventory_movements (
  id bigint generated by default as identity primary key,
  sku_key text not null,
  lot_id bigint references inventory_lots(id) on delete restrict,
  from_location_id bigint references inventory_locations(id) on delete restrict,
  to_location_id bigint references inventory_locations(id) on delete restrict,
  qty integer not null check (qty > 0),
  movement_type text not null check (movement_type in ('RECEIVE','MOVE','RESERVE','RELEASE','PICK','DISPATCH','ADJUSTMENT')),
  reference_type text not null default '',
  reference_id text not null default '',
  reason text not null default '',
  actor_name text not null default 'System',
  created_at timestamptz not null default now()
);

create table if not exists inventory_reservations (
  id bigint generated by default as identity primary key,
  order_id text not null,
  sku_key text not null,
  lot_id bigint not null references inventory_lots(id) on delete restrict,
  location_id bigint not null references inventory_locations(id) on delete restrict,
  qty_reserved integer not null check (qty_reserved > 0),
  qty_picked integer not null default 0 check (qty_picked >= 0 and qty_picked <= qty_reserved),
  status text not null default 'RESERVED' check (status in ('RESERVED','PICKED','DISPATCHED','RELEASED')),
  created_by text not null default 'System',
  created_at timestamptz not null default now(),
  unique (order_id, sku_key, lot_id, location_id)
);

create table if not exists inventory_adjustments (
  id bigint generated by default as identity primary key,
  sku_key text not null,
  lot_id bigint not null references inventory_lots(id) on delete restrict,
  location_id bigint not null references inventory_locations(id) on delete restrict,
  system_qty integer not null check (system_qty >= 0),
  counted_qty integer not null check (counted_qty >= 0),
  delta integer not null,
  reason text not null,
  status text not null default 'PENDING' check (status in ('PENDING','APPROVED','REJECTED')),
  submitted_by text not null default 'System',
  reviewed_by text not null default '',
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

-- Superadmin activity feed. Every warehouse action writes a durable entry so
-- notifications are shared across devices and survive browser refreshes.
create table if not exists admin_notifications (
  id bigint generated by default as identity primary key,
  action text not null default 'ACTIVITY',
  title text not null,
  detail text not null default '',
  product_name text not null default '',
  sku_key text not null default '',
  location text not null default '',
  qty integer not null default 0,
  actor_name text not null default 'Warehouse staff',
  created_at timestamptz not null default now()
);

create index if not exists idx_inventory_balances_sku on inventory_balances (sku_key);
create index if not exists idx_inventory_balances_location on inventory_balances (location_id);
create index if not exists idx_inventory_movements_sku_created on inventory_movements (sku_key, created_at desc);
create index if not exists idx_inventory_reservations_order on inventory_reservations (order_id, status);
create index if not exists idx_inventory_lots_sku_received on inventory_lots (sku_key, received_at);
create index if not exists idx_admin_notifications_created on admin_notifications (created_at desc);

insert into inventory_locations (code, name, storage_type) values
  ('RECEIVING', 'Receiving / Pending Putaway', 'RECEIVING'),
  ('PICKED', 'Picked / Dispatch Staging', 'PICKED'),
  ('DAMAGED', 'Damaged / Quarantine', 'DAMAGED'),
  ('DISPATCHED', 'Dispatched', 'DISPATCHED')
on conflict (code) do nothing;

create or replace function public.inventory_location_id(p_code text, p_type text default 'SHELF')
returns bigint
language plpgsql
as $$
declare
  result_id bigint;
begin
  if nullif(trim(coalesce(p_code, '')), '') is null then
    raise exception 'Inventory location is required';
  end if;
  insert into inventory_locations (code, name, storage_type)
  values (trim(p_code), trim(p_code), upper(coalesce(p_type, 'SHELF')))
  on conflict (code) do update set active = true
  returning id into result_id;
  if result_id is null then
    select id into result_id from inventory_locations where code = trim(p_code);
  end if;
  return result_id;
end;
$$;

create or replace function public.inventory_receive(
  p_sku_key text, p_barcode text, p_stock_no text, p_product_name text,
  p_qty integer, p_location_code text, p_package_type text, p_lot_code text,
  p_source_reference text, p_actor_name text
)
returns jsonb
language plpgsql
as $$
declare
  v_lot_id bigint;
  v_location_id bigint;
  v_balance_id bigint;
  v_lot_code text := coalesce(nullif(trim(p_lot_code), ''), 'LOT-' || to_char(clock_timestamp(), 'YYYYMMDDHH24MISSMS'));
  v_location_type text := case when upper(coalesce(p_package_type, 'EACH')) in ('CARTON','SACK','PALLET','OTHER') then 'BULK' else 'RECEIVING' end;
begin
  if coalesce(p_qty, 0) <= 0 then raise exception 'Receiving quantity must be greater than zero'; end if;
  if nullif(trim(coalesce(p_source_reference, '')), '') is not null and exists (
    select 1 from inventory_lots
    where sku_key = trim(p_sku_key) and source_reference = trim(p_source_reference)
  ) then
    raise exception 'This receiving reference has already been recorded for this product';
  end if;
  v_location_id := inventory_location_id(coalesce(nullif(trim(p_location_code), ''), 'RECEIVING'), v_location_type);
  insert into inventory_lots (sku_key, barcode, stock_no, product_name, lot_code, package_type, received_qty, source_reference, created_by)
  values (trim(p_sku_key), coalesce(p_barcode, ''), coalesce(p_stock_no, ''), coalesce(p_product_name, ''), v_lot_code, upper(coalesce(p_package_type, 'EACH')), p_qty, coalesce(p_source_reference, ''), coalesce(p_actor_name, 'System'))
  returning id into v_lot_id;
  insert into inventory_balances (sku_key, lot_id, location_id, qty_on_hand)
  values (trim(p_sku_key), v_lot_id, v_location_id, p_qty)
  returning id into v_balance_id;
  insert into inventory_movements (sku_key, lot_id, to_location_id, qty, movement_type, reference_type, reference_id, actor_name)
  values (trim(p_sku_key), v_lot_id, v_location_id, p_qty, 'RECEIVE', 'RECEIPT', v_lot_code, coalesce(p_actor_name, 'System'));
  return jsonb_build_object('lotId', v_lot_id, 'balanceId', v_balance_id, 'skuKey', trim(p_sku_key), 'qty', p_qty, 'location', coalesce(nullif(trim(p_location_code), ''), 'RECEIVING'));
end;
$$;

create or replace function public.inventory_move(
  p_sku_key text, p_lot_id bigint, p_from_location text, p_to_location text,
  p_qty integer, p_actor_name text, p_reason text default '', p_to_type text default 'SHELF'
)
returns jsonb
language plpgsql
as $$
declare
  v_source inventory_balances%rowtype;
  v_from_id bigint;
  v_to_id bigint;
  v_dest_id bigint;
  v_to_type text := case when upper(trim(coalesce(p_to_location, ''))) in ('RECEIVING','PICKED','DAMAGED','DISPATCHED') then upper(trim(p_to_location)) else upper(coalesce(p_to_type, 'SHELF')) end;
begin
  if coalesce(p_qty, 0) <= 0 then raise exception 'Move quantity must be greater than zero'; end if;
  select id into v_from_id from inventory_locations where code = trim(p_from_location) for share;
  if v_from_id is null then raise exception 'Source inventory location not found'; end if;
  select * into v_source from inventory_balances where sku_key = trim(p_sku_key) and lot_id = p_lot_id and location_id = v_from_id for update;
  if v_source.id is null then raise exception 'Source inventory balance not found'; end if;
  if p_qty > v_source.qty_on_hand - v_source.qty_reserved then raise exception 'Move quantity exceeds available quantity at source'; end if;
  v_to_id := inventory_location_id(trim(p_to_location), v_to_type);
  update inventory_balances set qty_on_hand = qty_on_hand - p_qty, updated_at = now() where id = v_source.id;
  insert into inventory_balances (sku_key, lot_id, location_id, qty_on_hand)
  values (trim(p_sku_key), p_lot_id, v_to_id, p_qty)
  on conflict (lot_id, location_id) do update set qty_on_hand = inventory_balances.qty_on_hand + excluded.qty_on_hand, updated_at = now()
  returning id into v_dest_id;
  insert into inventory_movements (sku_key, lot_id, from_location_id, to_location_id, qty, movement_type, reason, actor_name)
  values (trim(p_sku_key), p_lot_id, v_from_id, v_to_id, p_qty, 'MOVE', coalesce(p_reason, ''), coalesce(p_actor_name, 'System'));
  return jsonb_build_object('sourceBalanceId', v_source.id, 'destinationBalanceId', v_dest_id, 'qty', p_qty);
end;
$$;

create or replace function public.inventory_putaway(
  p_sku_key text, p_qty integer, p_to_location text, p_package_type text, p_actor_name text
)
returns jsonb
language plpgsql
as $$
declare
  r record;
  v_remaining integer := p_qty;
  v_take integer;
  v_to_id bigint;
  v_dest_id bigint;
  v_to_type text := case when upper(coalesce(p_package_type, 'EACH')) in ('CARTON','SACK','PALLET','OTHER') then 'BULK' else 'SHELF' end;
begin
  if coalesce(p_qty, 0) <= 0 then raise exception 'Putaway quantity must be greater than zero'; end if;
  v_to_id := inventory_location_id(trim(p_to_location), v_to_type);
  for r in
    select b.*, l.code as source_code
    from inventory_balances b join inventory_locations l on l.id = b.location_id
    join inventory_lots lot on lot.id = b.lot_id
    where b.sku_key = trim(p_sku_key) and b.qty_on_hand - b.qty_reserved > 0
      and l.storage_type in ('RECEIVING','BULK','SHELF')
    order by lot.received_at, b.id
    for update of b
  loop
    exit when v_remaining <= 0;
    if r.location_id = v_to_id then
      v_take := least(v_remaining, r.qty_on_hand - r.qty_reserved);
      v_remaining := v_remaining - v_take;
    else
      v_take := least(v_remaining, r.qty_on_hand - r.qty_reserved);
      update inventory_balances set qty_on_hand = qty_on_hand - v_take, updated_at = now() where id = r.id;
      insert into inventory_balances (sku_key, lot_id, location_id, qty_on_hand)
      values (r.sku_key, r.lot_id, v_to_id, v_take)
      on conflict (lot_id, location_id) do update set qty_on_hand = inventory_balances.qty_on_hand + excluded.qty_on_hand, updated_at = now()
      returning id into v_dest_id;
      insert into inventory_movements (sku_key, lot_id, from_location_id, to_location_id, qty, movement_type, reason, actor_name)
      values (r.sku_key, r.lot_id, r.location_id, v_to_id, v_take, 'MOVE', 'Putaway', coalesce(p_actor_name, 'System'));
      v_remaining := v_remaining - v_take;
    end if;
  end loop;
  if v_remaining > 0 then raise exception 'Putaway quantity exceeds available warehouse stock'; end if;
  return jsonb_build_object('skuKey', trim(p_sku_key), 'putAway', p_qty, 'location', trim(p_to_location));
end;
$$;

create or replace function public.inventory_reserve(
  p_order_id text, p_sku_key text, p_qty integer, p_actor_name text
)
returns jsonb
language plpgsql
as $$
declare
  v_balance record;
  v_remaining integer := p_qty;
  v_take integer;
  v_total integer := 0;
begin
  if coalesce(p_qty, 0) <= 0 then raise exception 'Reservation quantity must be greater than zero'; end if;
  if exists (select 1 from inventory_reservations where order_id = p_order_id and sku_key = p_sku_key and status in ('RESERVED','PICKED')) then
    raise exception 'This order already has an active reservation for this SKU';
  end if;
  for v_balance in
    select b.*, l.code as location_code
    from inventory_balances b
    join inventory_locations l on l.id = b.location_id
    join inventory_lots lot on lot.id = b.lot_id
    where b.sku_key = trim(p_sku_key) and b.qty_on_hand - b.qty_reserved > 0
      and l.storage_type in ('RECEIVING','BULK','SHELF')
    order by lot.received_at, b.id
    for update of b
  loop
    exit when v_remaining <= 0;
    v_take := least(v_remaining, v_balance.qty_on_hand - v_balance.qty_reserved);
    update inventory_balances set qty_reserved = qty_reserved + v_take, updated_at = now() where id = v_balance.id;
    insert into inventory_reservations (order_id, sku_key, lot_id, location_id, qty_reserved, created_by)
    values (p_order_id, trim(p_sku_key), v_balance.lot_id, v_balance.location_id, v_take, coalesce(p_actor_name, 'System'));
    insert into inventory_movements (sku_key, lot_id, from_location_id, qty, movement_type, reference_type, reference_id, actor_name)
    values (trim(p_sku_key), v_balance.lot_id, v_balance.location_id, v_take, 'RESERVE', 'ORDER', p_order_id, coalesce(p_actor_name, 'System'));
    v_remaining := v_remaining - v_take;
    v_total := v_total + v_take;
  end loop;
  if v_remaining > 0 then raise exception 'Insufficient available quantity for reservation'; end if;
  return jsonb_build_object('orderId', p_order_id, 'skuKey', trim(p_sku_key), 'reserved', v_total);
end;
$$;

create or replace function public.inventory_reserve_order(p_order_id text, p_items jsonb, p_actor_name text)
returns jsonb
language plpgsql
as $$
declare
  item jsonb;
  total_qty integer := 0;
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'At least one order item is required'; end if;
  for item in select value from jsonb_array_elements(p_items) loop
    if coalesce((item->>'qty')::integer, 0) <= 0 or nullif(trim(item->>'skuKey'), '') is null then raise exception 'Every order item needs a SKU and positive quantity'; end if;
    perform inventory_reserve(p_order_id, item->>'skuKey', (item->>'qty')::integer, p_actor_name);
    total_qty := total_qty + (item->>'qty')::integer;
  end loop;
  return jsonb_build_object('orderId', p_order_id, 'reserved', total_qty);
end;
$$;

create or replace function public.inventory_release_order(p_order_id text, p_actor_name text)
returns jsonb
language plpgsql
as $$
declare r record; total_qty integer := 0;
begin
  for r in select * from inventory_reservations where order_id = p_order_id and status = 'RESERVED' for update loop
    update inventory_balances set qty_reserved = qty_reserved - r.qty_reserved, updated_at = now() where lot_id = r.lot_id and location_id = r.location_id and qty_reserved >= r.qty_reserved;
    update inventory_reservations set status = 'RELEASED' where id = r.id;
    insert into inventory_movements (sku_key, lot_id, from_location_id, qty, movement_type, reference_type, reference_id, actor_name)
    values (r.sku_key, r.lot_id, r.location_id, r.qty_reserved, 'RELEASE', 'ORDER', p_order_id, coalesce(p_actor_name, 'System'));
    total_qty := total_qty + r.qty_reserved;
  end loop;
  return jsonb_build_object('orderId', p_order_id, 'released', total_qty);
end;
$$;

create or replace function public.inventory_summary(p_sku_key text)
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'skuKey', p_sku_key,
    'onHand', coalesce(sum(b.qty_on_hand), 0),
    'reserved', coalesce(sum(b.qty_reserved), 0),
    'available', coalesce(sum(b.qty_on_hand - b.qty_reserved) filter (where l.storage_type in ('RECEIVING','BULK','SHELF')), 0),
    'receiving', coalesce(sum(b.qty_on_hand) filter (where l.storage_type = 'RECEIVING'), 0),
    'bulk', coalesce(sum(b.qty_on_hand) filter (where l.storage_type = 'BULK'), 0),
    'shelf', coalesce(sum(b.qty_on_hand) filter (where l.storage_type = 'SHELF'), 0),
    'picked', coalesce(sum(b.qty_on_hand) filter (where l.storage_type = 'PICKED'), 0)
  )
  from inventory_balances b join inventory_locations l on l.id = b.location_id
  where b.sku_key = p_sku_key;
$$;

-- Fast, auditable physical-count correction from the product inventory card.
-- Available and reserved remain derived values; staff correct an on-hand
-- bucket (on hand, receiving, bulk, or shelf) instead of overwriting totals.
create or replace function public.inventory_quick_adjust(
  p_sku_key text,
  p_barcode text,
  p_stock_no text,
  p_product_name text,
  p_storage_type text,
  p_target_qty integer,
  p_reason text,
  p_actor_name text
)
returns jsonb
language plpgsql
as $$
declare
  v_type text := upper(trim(coalesce(p_storage_type, 'ON_HAND')));
  v_current integer := 0;
  v_delta integer := 0;
  v_remaining integer := 0;
  v_destination_type text;
  v_location_id bigint;
  v_lot_id bigint;
  v_old integer;
  v_new integer;
  v_take integer;
  v_adjustment_id bigint;
  r record;
begin
  if nullif(trim(coalesce(p_sku_key, '')), '') is null then raise exception 'SKU is required'; end if;
  if v_type not in ('ON_HAND', 'RECEIVING', 'BULK', 'SHELF') then raise exception 'Unsupported inventory bucket'; end if;
  if coalesce(p_target_qty, -1) < 0 then raise exception 'Quantity cannot be negative'; end if;
  if nullif(trim(coalesce(p_reason, '')), '') is null then raise exception 'A reason is required'; end if;

  select coalesce(sum(b.qty_on_hand), 0)::integer into v_current
  from inventory_balances b
  join inventory_locations l on l.id = b.location_id
  where b.sku_key = trim(p_sku_key)
    and ((v_type = 'ON_HAND' and l.storage_type in ('RECEIVING','BULK','SHELF','PICKED','DAMAGED','DISPATCHED'))
      or (v_type <> 'ON_HAND' and l.storage_type = v_type));

  v_delta := p_target_qty - v_current;
  if v_delta = 0 then
    return jsonb_build_object('skuKey', trim(p_sku_key), 'storageType', v_type, 'previousQty', v_current, 'targetQty', p_target_qty, 'delta', 0);
  end if;

  if v_delta > 0 then
    v_destination_type := case when v_type = 'ON_HAND' then 'RECEIVING' else v_type end;
    select b.id, b.lot_id, b.location_id, b.qty_on_hand, b.qty_reserved, l.code
      into r
    from inventory_balances b
    join inventory_locations l on l.id = b.location_id
    where b.sku_key = trim(p_sku_key) and l.storage_type = v_destination_type
    order by b.qty_on_hand desc, b.id
    limit 1
    for update;

    if found then
      v_old := r.qty_on_hand;
      v_new := v_old + v_delta;
      update inventory_balances set qty_on_hand = v_new, updated_at = now() where id = r.id;
      insert into inventory_adjustments (sku_key, lot_id, location_id, system_qty, counted_qty, delta, reason, status, submitted_by, reviewed_by, reviewed_at)
      values (trim(p_sku_key), r.lot_id, r.location_id, v_old, v_new, v_delta, trim(p_reason), 'APPROVED', coalesce(p_actor_name, 'System'), coalesce(p_actor_name, 'System'), now())
      returning id into v_adjustment_id;
      insert into inventory_movements (sku_key, lot_id, to_location_id, qty, movement_type, reference_type, reference_id, reason, actor_name)
      values (trim(p_sku_key), r.lot_id, r.location_id, v_delta, 'ADJUSTMENT', 'QUICK_ADJUSTMENT', v_adjustment_id::text, trim(p_reason), coalesce(p_actor_name, 'System'));
    else
      v_location_id := inventory_location_id(v_destination_type, v_destination_type);
      insert into inventory_lots (sku_key, barcode, stock_no, product_name, lot_code, package_type, received_qty, source_reference, created_by)
      values (trim(p_sku_key), coalesce(p_barcode, ''), coalesce(p_stock_no, ''), coalesce(p_product_name, ''), 'QUICK-' || substr(md5(random()::text || clock_timestamp()::text), 1, 24), case when v_destination_type = 'BULK' then 'CARTON' else 'EACH' end, v_delta, 'QUICK_ADJUSTMENT', coalesce(p_actor_name, 'System'))
      returning id into v_lot_id;
      insert into inventory_balances (sku_key, lot_id, location_id, qty_on_hand)
      values (trim(p_sku_key), v_lot_id, v_location_id, v_delta);
      insert into inventory_adjustments (sku_key, lot_id, location_id, system_qty, counted_qty, delta, reason, status, submitted_by, reviewed_by, reviewed_at)
      values (trim(p_sku_key), v_lot_id, v_location_id, 0, v_delta, v_delta, trim(p_reason), 'APPROVED', coalesce(p_actor_name, 'System'), coalesce(p_actor_name, 'System'), now())
      returning id into v_adjustment_id;
      insert into inventory_movements (sku_key, lot_id, to_location_id, qty, movement_type, reference_type, reference_id, reason, actor_name)
      values (trim(p_sku_key), v_lot_id, v_location_id, v_delta, 'ADJUSTMENT', 'QUICK_ADJUSTMENT', v_adjustment_id::text, trim(p_reason), coalesce(p_actor_name, 'System'));
    end if;
  else
    v_remaining := abs(v_delta);
    for r in
      select b.id, b.lot_id, b.location_id, b.qty_on_hand, b.qty_reserved
      from inventory_balances b
      join inventory_locations l on l.id = b.location_id
      where b.sku_key = trim(p_sku_key)
        and ((v_type = 'ON_HAND' and l.storage_type in ('RECEIVING','BULK','SHELF','PICKED','DAMAGED','DISPATCHED'))
          or (v_type <> 'ON_HAND' and l.storage_type = v_type))
        and b.qty_on_hand > b.qty_reserved
      order by b.qty_on_hand desc, b.id
      for update
    loop
      exit when v_remaining = 0;
      v_take := least(v_remaining, r.qty_on_hand - r.qty_reserved);
      v_old := r.qty_on_hand;
      v_new := v_old - v_take;
      update inventory_balances set qty_on_hand = v_new, updated_at = now() where id = r.id;
      insert into inventory_adjustments (sku_key, lot_id, location_id, system_qty, counted_qty, delta, reason, status, submitted_by, reviewed_by, reviewed_at)
      values (trim(p_sku_key), r.lot_id, r.location_id, v_old, v_new, -v_take, trim(p_reason), 'APPROVED', coalesce(p_actor_name, 'System'), coalesce(p_actor_name, 'System'), now())
      returning id into v_adjustment_id;
      insert into inventory_movements (sku_key, lot_id, from_location_id, qty, movement_type, reference_type, reference_id, reason, actor_name)
      values (trim(p_sku_key), r.lot_id, r.location_id, v_take, 'ADJUSTMENT', 'QUICK_ADJUSTMENT', v_adjustment_id::text, trim(p_reason), coalesce(p_actor_name, 'System'));
      v_remaining := v_remaining - v_take;
    end loop;
    if v_remaining > 0 then raise exception 'Target quantity is below reserved or unavailable stock'; end if;
  end if;

  return jsonb_build_object('skuKey', trim(p_sku_key), 'storageType', v_type, 'previousQty', v_current, 'targetQty', p_target_qty, 'delta', v_delta);
end;
$$;

-- Dispatch goods directly from the receiving area. This is used when an
-- arriving product leaves for delivery before it has been put away.
create or replace function public.inventory_direct_dispatch(
  p_sku_key text,
  p_qty integer,
  p_delivery_reference text,
  p_actor_name text
)
returns jsonb
language plpgsql
as $$
declare
  r record;
  v_remaining integer := p_qty;
  v_available integer := 0;
  v_take integer;
begin
  if nullif(trim(coalesce(p_sku_key, '')), '') is null then raise exception 'SKU is required'; end if;
  if coalesce(p_qty, 0) <= 0 then raise exception 'Delivery quantity must be greater than zero'; end if;
  if nullif(trim(coalesce(p_delivery_reference, '')), '') is null then raise exception 'A delivery reference is required'; end if;
  if exists (
    select 1 from inventory_movements
    where sku_key = trim(p_sku_key)
      and reference_type = 'DIRECT_DELIVERY'
      and reference_id = trim(p_delivery_reference)
  ) then
    raise exception 'This delivery reference has already been recorded for this product';
  end if;

  select coalesce(sum(b.qty_on_hand - b.qty_reserved), 0) into v_available
  from inventory_balances b
  join inventory_locations l on l.id = b.location_id
  where b.sku_key = trim(p_sku_key) and l.storage_type = 'RECEIVING';
  if v_available < p_qty then
    raise exception 'Only % unreserved unit(s) are available in Receiving', v_available;
  end if;

  for r in
    select b.id as balance_id, b.lot_id, b.location_id, b.qty_on_hand, b.qty_reserved
    from inventory_balances b
    join inventory_locations l on l.id = b.location_id
    join inventory_lots lot on lot.id = b.lot_id
    where b.sku_key = trim(p_sku_key) and l.storage_type = 'RECEIVING' and b.qty_on_hand > b.qty_reserved
    order by lot.received_at, b.id
    for update of b
  loop
    exit when v_remaining = 0;
    v_take := least(v_remaining, r.qty_on_hand - r.qty_reserved);
    update inventory_balances set qty_on_hand = qty_on_hand - v_take, updated_at = now() where id = r.balance_id;
    insert into inventory_movements (sku_key, lot_id, from_location_id, qty, movement_type, reference_type, reference_id, reason, actor_name)
    values (trim(p_sku_key), r.lot_id, r.location_id, v_take, 'DISPATCH', 'DIRECT_DELIVERY', trim(p_delivery_reference), 'Direct delivery from Receiving', coalesce(p_actor_name, 'System'));
    v_remaining := v_remaining - v_take;
  end loop;
  return jsonb_build_object('skuKey', trim(p_sku_key), 'dispatched', p_qty, 'deliveryReference', trim(p_delivery_reference), 'source', 'RECEIVING');
end;
$$;

-- Products whose physically recorded warehouse stock is higher than the
-- catalog/system on-hand value. These need review before more stock is moved.
create or replace function public.inventory_reconciliation_exceptions(p_limit integer default 50)
returns table (sku_key text, product_name text, barcode text, stock_no text, catalog_qty integer, physical_qty integer, excess_qty integer)
language sql
stable
as $$
  with physical as (
    select b.sku_key, coalesce(sum(b.qty_on_hand), 0)::integer as physical_qty
    from inventory_balances b
    join inventory_locations l on l.id = b.location_id
    where l.storage_type in ('RECEIVING', 'BULK', 'SHELF', 'PICKED')
    group by b.sku_key
  ), catalog as (
    select
      coalesce(nullif(lower(trim(barcode)), ''), nullif(lower(trim(stock_no)), '')) as sku_key,
      product_name, barcode, stock_no, coalesce(qty, 0)::integer as catalog_qty
    from products
  )
  select p.sku_key, c.product_name, c.barcode, c.stock_no, c.catalog_qty, p.physical_qty,
    (p.physical_qty - c.catalog_qty)::integer as excess_qty
  from physical p
  join catalog c on c.sku_key = p.sku_key
  where p.physical_qty > c.catalog_qty
  order by (p.physical_qty - c.catalog_qty) desc, c.product_name
  limit greatest(1, least(coalesce(p_limit, 50), 200));
$$;

create or replace function public.inventory_warehouse_summary()
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'onHand', coalesce(sum(b.qty_on_hand), 0),
    'reserved', coalesce(sum(b.qty_reserved), 0),
    'available', coalesce(sum(b.qty_on_hand - b.qty_reserved) filter (where l.storage_type in ('RECEIVING','BULK','SHELF')), 0),
    'receiving', coalesce(sum(b.qty_on_hand) filter (where l.storage_type = 'RECEIVING'), 0),
    'bulk', coalesce(sum(b.qty_on_hand) filter (where l.storage_type = 'BULK'), 0),
    'shelf', coalesce(sum(b.qty_on_hand) filter (where l.storage_type = 'SHELF'), 0),
    'picked', coalesce(sum(b.qty_on_hand) filter (where l.storage_type = 'PICKED'), 0),
    'skuCount', (select count(distinct sku_key) from inventory_balances where qty_on_hand > 0)
  )
  from inventory_balances b join inventory_locations l on l.id = b.location_id;
$$;

-- Exact warehouse activity totals for the current calendar day. This is kept
-- separate from the short recent-activity list shown in Superadmin.
create or replace function public.inventory_daily_activity_summary()
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'total', count(*),
    'received', coalesce(sum(qty) filter (where movement_type = 'RECEIVE'), 0),
    'delivered', coalesce(sum(qty) filter (where reference_type = 'DIRECT_DELIVERY' or movement_type = 'DISPATCH'), 0),
    'adjustments', count(*) filter (where movement_type = 'ADJUSTMENT')
  )
  from inventory_movements
  where created_at >= date_trunc('day', now());
$$;

create or replace function public.inventory_pick_order(p_order_id text, p_actor_name text)
returns jsonb
language plpgsql
as $$
declare
  r record;
  v_picked_id bigint;
  total_qty integer := 0;
begin
  for r in
    select ir.*, b.qty_on_hand, l.code as source_code
    from inventory_reservations ir
    join inventory_balances b on b.lot_id = ir.lot_id and b.location_id = ir.location_id
    join inventory_locations l on l.id = ir.location_id
    where ir.order_id = p_order_id and ir.status = 'RESERVED'
    for update of ir, b
  loop
    if r.qty_reserved > r.qty_picked and r.qty_reserved > r.qty_on_hand then
      raise exception 'Reserved quantity is no longer physically available at source';
    end if;
    update inventory_balances set qty_on_hand = qty_on_hand - r.qty_reserved, qty_reserved = qty_reserved - r.qty_reserved, updated_at = now() where id = r.id;
    insert into inventory_balances (sku_key, lot_id, location_id, qty_on_hand)
    select r.sku_key, r.lot_id, id, r.qty_reserved from inventory_locations where code = 'PICKED'
    on conflict (lot_id, location_id) do update set qty_on_hand = inventory_balances.qty_on_hand + excluded.qty_on_hand, updated_at = now()
    returning id into v_picked_id;
    update inventory_reservations set status = 'PICKED', qty_picked = qty_reserved where id = r.id;
    insert into inventory_movements (sku_key, lot_id, from_location_id, to_location_id, qty, movement_type, reference_type, reference_id, actor_name)
    select r.sku_key, r.lot_id, r.location_id, id, r.qty_reserved, 'PICK', 'ORDER', p_order_id, coalesce(p_actor_name, 'System') from inventory_locations where code = 'PICKED';
    total_qty := total_qty + r.qty_reserved;
  end loop;
  return jsonb_build_object('orderId', p_order_id, 'picked', total_qty);
end;
$$;

create or replace function public.inventory_dispatch_order(p_order_id text, p_actor_name text)
returns jsonb
language plpgsql
as $$
declare
  r record;
  v_dispatch_id bigint;
  total_qty integer := 0;
begin
  for r in
    select ir.*, b.id as balance_id, b.qty_on_hand, b.location_id as picked_location_id
    from inventory_reservations ir
    join inventory_balances b on b.lot_id = ir.lot_id and b.sku_key = ir.sku_key
    join inventory_locations l on l.id = b.location_id and l.code = 'PICKED'
    where ir.order_id = p_order_id and ir.status = 'PICKED'
    for update of ir, b
  loop
    if r.qty_picked > r.qty_on_hand then raise exception 'Picked quantity is no longer available in dispatch staging'; end if;
    update inventory_balances set qty_on_hand = qty_on_hand - r.qty_picked, updated_at = now() where id = r.balance_id;
    update inventory_reservations set status = 'DISPATCHED' where id = r.id;
    insert into inventory_movements (sku_key, lot_id, from_location_id, qty, movement_type, reference_type, reference_id, actor_name)
    values (r.sku_key, r.lot_id, r.picked_location_id, r.qty_picked, 'DISPATCH', 'ORDER', p_order_id, coalesce(p_actor_name, 'System'));
    total_qty := total_qty + r.qty_picked;
  end loop;
  return jsonb_build_object('orderId', p_order_id, 'dispatched', total_qty);
end;
$$;

create or replace function public.inventory_request_adjustment(
  p_sku_key text, p_lot_id bigint, p_location_code text, p_counted_qty integer,
  p_reason text, p_actor_name text
)
returns jsonb
language plpgsql
as $$
declare
  v_location_id bigint;
  v_system_qty integer;
  v_adjustment_id bigint;
begin
  if coalesce(p_counted_qty, -1) < 0 or nullif(trim(coalesce(p_reason, '')), '') is null then raise exception 'A non-negative count and reason are required'; end if;
  select id into v_location_id from inventory_locations where code = trim(p_location_code);
  if v_location_id is null then raise exception 'Inventory location not found'; end if;
  select qty_on_hand into v_system_qty from inventory_balances where sku_key = trim(p_sku_key) and lot_id = p_lot_id and location_id = v_location_id;
  if v_system_qty is null then raise exception 'Inventory balance not found'; end if;
  insert into inventory_adjustments (sku_key, lot_id, location_id, system_qty, counted_qty, delta, reason, submitted_by)
  values (trim(p_sku_key), p_lot_id, v_location_id, v_system_qty, p_counted_qty, p_counted_qty - v_system_qty, trim(p_reason), coalesce(p_actor_name, 'System'))
  returning id into v_adjustment_id;
  return jsonb_build_object('adjustmentId', v_adjustment_id, 'status', 'PENDING', 'delta', p_counted_qty - v_system_qty);
end;
$$;

create or replace function public.inventory_approve_adjustment(p_adjustment_id bigint, p_reviewer text)
returns jsonb
language plpgsql
as $$
declare
  a inventory_adjustments%rowtype;
  v_balance inventory_balances%rowtype;
begin
  select * into a from inventory_adjustments where id = p_adjustment_id and status = 'PENDING' for update;
  if a.id is null then raise exception 'Pending inventory adjustment not found'; end if;
  select * into v_balance from inventory_balances where sku_key = a.sku_key and lot_id = a.lot_id and location_id = a.location_id for update;
  if v_balance.id is null then raise exception 'Inventory balance not found'; end if;
  if a.counted_qty < v_balance.qty_reserved then raise exception 'Counted quantity cannot be below reserved quantity'; end if;
  update inventory_balances set qty_on_hand = a.counted_qty, updated_at = now() where id = v_balance.id;
  update inventory_adjustments set status = 'APPROVED', reviewed_by = coalesce(p_reviewer, 'System'), reviewed_at = now() where id = a.id;
  insert into inventory_movements (sku_key, lot_id, from_location_id, to_location_id, qty, movement_type, reference_type, reference_id, reason, actor_name)
  values (a.sku_key, a.lot_id, a.location_id, a.location_id, abs(a.delta), 'ADJUSTMENT', 'ADJUSTMENT', a.id::text, a.reason, coalesce(p_reviewer, 'System'));
  return jsonb_build_object('adjustmentId', a.id, 'status', 'APPROVED', 'delta', a.delta);
end;
$$;

create or replace function public.inventory_migrate_legacy(p_actor_name text default 'Legacy Migration')
returns jsonb
language plpgsql
as $$
declare
  v_lots integer := 0;
  v_balances integer := 0;
begin
  -- Product catalog quantity is the source of on-hand stock. Do not create
  -- inferred Receiving, Bulk, or Shelf balances from an import; those
  -- quantities begin at zero and are recorded only by warehouse actions.
  return jsonb_build_object('lotsCreated', 0, 'balancesCreated', 0, 'mode', 'catalog-on-hand');

  -- Imported catalog quantities are total warehouse stock, not a verified
  -- shelf count. Start every opening balance in Receiving; staff move only
  -- physically displayed units to a shelf during putaway.
  insert into inventory_locations (code, name, storage_type)
  select 'RECEIVING', 'Receiving', 'RECEIVING'
  from products p where coalesce(p.qty, 0) > 0
  limit 1
  on conflict (code) do nothing;

  insert into inventory_lots (sku_key, barcode, stock_no, product_name, lot_code, package_type, received_qty, source_reference, created_by)
  select
    coalesce(nullif(lower(trim(p.barcode)), ''), nullif(lower(trim(p.stock_no)), ''), 'id:' || p.id::text),
    p.barcode, p.stock_no, p.product_name, 'MIGRATED-' || p.id::text,
    case when coalesce(p.location_storage, '') ilike '%carton%' then 'CARTON' when coalesce(p.location_storage, '') ilike '%sack%' then 'SACK' else 'EACH' end,
    p.qty, 'products:' || p.id::text, coalesce(p_actor_name, 'Legacy Migration')
  from products p
  where coalesce(p.qty, 0) > 0
  on conflict (lot_code) do nothing;
  get diagnostics v_lots = row_count;

  insert into inventory_balances (sku_key, lot_id, location_id, qty_on_hand)
  select l.sku_key, l.id, il.id, l.received_qty
  from inventory_lots l
  join products p on l.lot_code = 'MIGRATED-' || p.id::text
  join inventory_locations il on il.code = 'RECEIVING'
  where l.lot_code like 'MIGRATED-%'
  on conflict (lot_id, location_id) do nothing;
  get diagnostics v_balances = row_count;

  insert into inventory_movements (sku_key, lot_id, to_location_id, qty, movement_type, reference_type, reference_id, reason, actor_name)
  select b.sku_key, b.lot_id, b.location_id, b.qty_on_hand, 'RECEIVE', 'MIGRATION', 'products:' || p.id::text, 'Opening balance migrated from products.qty', coalesce(p_actor_name, 'Legacy Migration')
  from inventory_balances b
  join inventory_lots l on l.id = b.lot_id
  join products p on l.lot_code = 'MIGRATED-' || p.id::text
  where not exists (select 1 from inventory_movements m where m.reference_type = 'MIGRATION' and m.reference_id = 'products:' || p.id::text);

  return jsonb_build_object('lotsCreated', v_lots, 'balancesCreated', v_balances);
end;
$$;

-- Realtime is used by the superadmin console for instant location updates.
do $$
begin
  alter publication supabase_realtime add table public.products;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.admin_notifications;
exception
  when duplicate_object then null;
end $$;
